## Appendix B: Otthers Accuracy Test Results

### The Number of Dimensions: 5 

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-5.txt',
              'data/accuracy-test/accuracy-test-10-5.txt',
              'data/accuracy-test/accuracy-test-20-5.txt',
              'data/accuracy-test/accuracy-test-50-5.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 10

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-10.txt',
              'data/accuracy-test/accuracy-test-10-10.txt',
              'data/accuracy-test/accuracy-test-20-10.txt',
              'data/accuracy-test/accuracy-test-50-10.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 20

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-20.txt',
              'data/accuracy-test/accuracy-test-10-20.txt',
              'data/accuracy-test/accuracy-test-20-20.txt',
              'data/accuracy-test/accuracy-test-50-20.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 50

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-50.txt',
              'data/accuracy-test/accuracy-test-10-50.txt',
              'data/accuracy-test/accuracy-test-20-50.txt',
              'data/accuracy-test/accuracy-test-50-50.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 100

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-100.txt',
              'data/accuracy-test/accuracy-test-10-100.txt',
              'data/accuracy-test/accuracy-test-20-100.txt',
              'data/accuracy-test/accuracy-test-50-100.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 200

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-200.txt',
              'data/accuracy-test/accuracy-test-10-200.txt',
              'data/accuracy-test/accuracy-test-20-200.txt',
              'data/accuracy-test/accuracy-test-50-200.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```

### The Number of Dimensions: 1000

```{r echo=FALSE, warning=FALSE, comment=""}
files <- c(
              'data/accuracy-test/accuracy-test-5-1000.txt',
              'data/accuracy-test/accuracy-test-10-1000.txt',
              'data/accuracy-test/accuracy-test-20-1000.txt',
              'data/accuracy-test/accuracy-test-50-1000.txt'
           )
for (i in 1:length(files)) {
  .file <- file(description = files[i], open = "r")
  print(readLines(.file))
  close(.file)
}
```
